"""
Company universe: a curated list of public companies with known outcomes.

Each entry has:
  - ticker:    stock symbol (used by yfinance)
  - cik:       SEC EDGAR company ID (used to pull 10-K filings)
  - name:      human-readable company name
  - bankruptcy_filing: 1 = filed for bankruptcy protection, 0 = public control
  - bankrupt: backward-compatible alias for bankruptcy_filing
  - sector:    industry group for dashboard filters
  - filing_date: bankruptcy filing date, used as the SEC filing cutoff
  - year_filed: year bankruptcy was filed (None if healthy)

The positive class is intentionally "bankruptcy filing" rather than final
liquidation or confirmed permanent failure. Training collection uses only
10-Ks filed before filing_date for positive examples.
"""

COMPANIES = [
    # ── BANKRUPT companies ─────────────────────────────────────────────────
    {
        "ticker": "ENRNQ",
        "cik": "0000101778",
        "name": "Enron Corp",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2001-12-02",
        "year_filed": 2001,
    },
    {
        "ticker": "LEHMQ",
        "cik": "0000806517",
        "name": "Lehman Brothers",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Financials",
        "filing_date": "2008-09-15",
        "year_filed": 2008,
    },
    {
        "ticker": "GM",
        "cik": "0000040730",
        "name": "General Motors (old)",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2009-06-01",
        "year_filed": 2009,
    },
    {
        "ticker": "SHLDQ",
        "cik": "0001310067",
        "name": "Sears Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2018-10-15",
        "year_filed": 2018,
    },
    {
        "ticker": "RSHCQ",
        "cik": "0000096289",
        "name": "RadioShack",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2015-02-05",
        "year_filed": 2015,
    },
    {
        "ticker": "BLOKQ",
        "cik": "0001085734",
        "name": "Blockbuster",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2010-09-23",
        "year_filed": 2010,
    },
    {
        "ticker": "KMART",
        "cik": "0000055067",
        "name": "Kmart",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Staples",
        "filing_date": "2002-01-22",
        "year_filed": 2002,
    },
    {
        "ticker": "WCOM",
        "cik": "0000723527",
        "name": "WorldCom / MCI",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Telecom",
        "filing_date": "2002-07-21",
        "year_filed": 2002,
    },
    {
        "ticker": "WAMUQ",
        "cik": "0000933136",
        "name": "Washington Mutual",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Financials",
        "filing_date": "2008-09-26",
        "year_filed": 2008,
    },
    {
        "ticker": "CHTRQ",
        "cik": "0001091334",
        "name": "Charter Communications (old)",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Telecom",
        "filing_date": "2009-03-27",
        "year_filed": 2009,
    },
    {
        "ticker": "PCRXQ",
        "cik": "0001419041",
        "name": "Pactera (Nortel Networks)",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Technology",
        "filing_date": "2009-01-14",
        "year_filed": 2009,
    },
    {
        "ticker": "NORX",
        "cik": "0000072162",
        "name": "Nortel Networks",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Technology",
        "filing_date": "2009-01-14",
        "year_filed": 2009,
    },
    {
        "ticker": "AERAQ",
        "cik": "0000006201",
        "name": "American Airlines (old)",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2011-11-29",
        "year_filed": 2011,
    },
    {
        "ticker": "DALRQ",
        "cik": "0000027904",
        "name": "Delta Air Lines (old)",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2005-09-14",
        "year_filed": 2005,
    },
    {
        "ticker": "PCG",
        "cik": "0001004980",
        "name": "PG&E Corp",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Utilities",
        "filing_date": "2019-01-29",
        "year_filed": 2019,
    },
    {
        "ticker": "HTZGQ",
        "cik": "0001657853",
        "name": "Hertz Global Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2020-05-22",
        "year_filed": 2020,
    },
    {
        "ticker": "JCPNQ",
        "cik": "0001166126",
        "name": "J. C. Penney Company",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2020-05-15",
        "year_filed": 2020,
    },
    {
        "ticker": "CHKAQ",
        "cik": "0000895126",
        "name": "Chesapeake Energy",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2020-06-28",
        "year_filed": 2020,
    },
    {
        "ticker": "WLL",
        "cik": "0001255474",
        "name": "Whiting Petroleum",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2020-04-01",
        "year_filed": 2020,
    },
    {
        "ticker": "DOFSQ",
        "cik": "0000949039",
        "name": "Diamond Offshore Drilling",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2020-04-26",
        "year_filed": 2020,
    },
    {
        "ticker": "BTU",
        "cik": "0001064728",
        "name": "Peabody Energy",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2016-04-13",
        "year_filed": 2016,
    },
    {
        "ticker": "ARCH",
        "cik": "0001037676",
        "name": "Arch Coal",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2016-01-11",
        "year_filed": 2016,
    },
    {
        "ticker": "SUNEQ",
        "cik": "0000945436",
        "name": "SunEdison",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2016-04-21",
        "year_filed": 2016,
    },
    {
        "ticker": "CZR",
        "cik": "0000858339",
        "name": "Caesars Entertainment Operating Co",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2015-01-15",
        "year_filed": 2015,
    },
    {
        "ticker": "EFH",
        "cik": "0001023291",
        "name": "Energy Future Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Utilities",
        "filing_date": "2014-04-29",
        "year_filed": 2014,
    },
    {
        "ticker": "IHRTQ",
        "cik": "0001400891",
        "name": "iHeartMedia",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2018-03-14",
        "year_filed": 2018,
    },
    {
        "ticker": "FTRCQ",
        "cik": "0000020520",
        "name": "Frontier Communications",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2020-04-14",
        "year_filed": 2020,
    },
    {
        "ticker": "WINMQ",
        "cik": "0001282266",
        "name": "Windstream Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2019-02-25",
        "year_filed": 2019,
    },
    {
        "ticker": "MNK",
        "cik": "0001567892",
        "name": "Mallinckrodt",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Healthcare",
        "filing_date": "2020-10-12",
        "year_filed": 2020,
    },
    {
        "ticker": "INTEQ",
        "cik": "0001525773",
        "name": "Intelsat",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2020-05-13",
        "year_filed": 2020,
    },
    {
        "ticker": "GNC",
        "cik": "0001502034",
        "name": "GNC Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Staples",
        "filing_date": "2020-06-23",
        "year_filed": 2020,
    },
    {
        "ticker": "REV",
        "cik": "0000887921",
        "name": "Revlon",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Staples",
        "filing_date": "2022-06-15",
        "year_filed": 2022,
    },
    {
        "ticker": "BBBYQ",
        "cik": "0000886158",
        "name": "Bed Bath & Beyond",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2023-04-23",
        "year_filed": 2023,
    },
    {
        "ticker": "SIVBQ",
        "cik": "0000719739",
        "name": "SVB Financial Group",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Financials",
        "filing_date": "2023-03-17",
        "year_filed": 2023,
    },
    {
        "ticker": "RIDEQ",
        "cik": "0001759546",
        "name": "Lordstown Motors",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2023-06-27",
        "year_filed": 2023,
    },
    {
        "ticker": "SDCCQ",
        "cik": "0001775625",
        "name": "SmileDirectClub",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Healthcare",
        "filing_date": "2023-09-29",
        "year_filed": 2023,
    },
    {
        "ticker": "WEWKQ",
        "cik": "0001813756",
        "name": "WeWork",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Real Estate",
        "filing_date": "2023-11-06",
        "year_filed": 2023,
    },
    {
        "ticker": "RAD",
        "cik": "0000084129",
        "name": "Rite Aid",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Staples",
        "filing_date": "2023-10-15",
        "year_filed": 2023,
    },
    {
        "ticker": "YELLQ",
        "cik": "0000716006",
        "name": "Yellow Corp",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2023-08-06",
        "year_filed": 2023,
    },
    {
        "ticker": "VORBQ",
        "cik": "0001843388",
        "name": "Virgin Orbit",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2023-04-04",
        "year_filed": 2023,
    },
    {
        "ticker": "PRTYQ",
        "cik": "0001592058",
        "name": "Party City Holdco",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2023-01-17",
        "year_filed": 2023,
    },
    {
        "ticker": "TUP",
        "cik": "0001008654",
        "name": "Tupperware Brands",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Staples",
        "filing_date": "2024-09-17",
        "year_filed": 2024,
    },
    {
        "ticker": "EXPRQ",
        "cik": "0001483510",
        "name": "Express",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-04-22",
        "year_filed": 2024,
    },
    {
        "ticker": "FSRN",
        "cik": "0001720990",
        "name": "Fisker",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-06-17",
        "year_filed": 2024,
    },
    {
        "ticker": "NVTAQ",
        "cik": "0001501134",
        "name": "Invitae",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Healthcare",
        "filing_date": "2024-02-13",
        "year_filed": 2024,
    },
    {
        "ticker": "CANOQ",
        "cik": "0001800682",
        "name": "Cano Health",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Healthcare",
        "filing_date": "2024-02-04",
        "year_filed": 2024,
    },
    {
        "ticker": "AUDAQ",
        "cik": "0001067837",
        "name": "Audacy",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2024-01-07",
        "year_filed": 2024,
    },
    {
        "ticker": "BIG",
        "cik": "0000768835",
        "name": "Big Lots",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-09-09",
        "year_filed": 2024,
    },
    {
        "ticker": "CONNQ",
        "cik": "0001223389",
        "name": "Conn's Inc",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-07-23",
        "year_filed": 2024,
    },
    {
        "ticker": "LLFLQ",
        "cik": "0001396033",
        "name": "LL Flooring Holdings",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-08-11",
        "year_filed": 2024,
    },
    {
        "ticker": "JOANQ",
        "cik": "0001834585",
        "name": "JOANN Inc",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-03-18",
        "year_filed": 2024,
    },
    {
        "ticker": "EVA",
        "cik": "0001592057",
        "name": "Enviva Inc",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Energy",
        "filing_date": "2024-03-12",
        "year_filed": 2024,
    },
    {
        "ticker": "ISUNQ",
        "cik": "0001634447",
        "name": "iSun Inc",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Industrials",
        "filing_date": "2024-06-03",
        "year_filed": 2024,
    },
    {
        "ticker": "CRGEQ",
        "cik": "0001277250",
        "name": "Charge Enterprises",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Communication Services",
        "filing_date": "2024-04-24",
        "year_filed": 2024,
    },
    {
        "ticker": "IDICQ",
        "cik": "0001698113",
        "name": "PARTS iD",
        "bankrupt": 1,
        "bankruptcy_filing": 1,
        "sector": "Consumer Discretionary",
        "filing_date": "2024-02-05",
        "year_filed": 2024,
    },

    # ── HEALTHY companies ──────────────────────────────────────────────────
    {
        "ticker": "AAPL",
        "cik": "0000320193",
        "name": "Apple Inc",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "MSFT",
        "cik": "0000789019",
        "name": "Microsoft Corp",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "GOOGL",
        "cik": "0001652044",
        "name": "Alphabet Inc",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "AMZN",
        "cik": "0001018724",
        "name": "Amazon.com",
        "bankrupt": 0,
        "sector": "Consumer Discretionary",
        "year_filed": None,
    },
    {
        "ticker": "JPM",
        "cik": "0000019617",
        "name": "JPMorgan Chase",
        "bankrupt": 0,
        "sector": "Financials",
        "year_filed": None,
    },
    {
        "ticker": "JNJ",
        "cik": "0000200406",
        "name": "Johnson & Johnson",
        "bankrupt": 0,
        "sector": "Healthcare",
        "year_filed": None,
    },
    {
        "ticker": "XOM",
        "cik": "0000034088",
        "name": "ExxonMobil",
        "bankrupt": 0,
        "sector": "Energy",
        "year_filed": None,
    },
    {
        "ticker": "WMT",
        "cik": "0000104169",
        "name": "Walmart",
        "bankrupt": 0,
        "sector": "Consumer Staples",
        "year_filed": None,
    },
    {
        "ticker": "VZ",
        "cik": "0000732712",
        "name": "Verizon Communications",
        "bankrupt": 0,
        "sector": "Telecom",
        "year_filed": None,
    },
    {
        "ticker": "GE",
        "cik": "0000040554",
        "name": "General Electric",
        "bankrupt": 0,
        "sector": "Industrials",
        "year_filed": None,
    },
    {
        "ticker": "BA",
        "cik": "0000012927",
        "name": "Boeing Co",
        "bankrupt": 0,
        "sector": "Industrials",
        "year_filed": None,
    },
    {
        "ticker": "T",
        "cik": "0000732717",
        "name": "AT&T",
        "bankrupt": 0,
        "sector": "Telecom",
        "year_filed": None,
    },
    {
        "ticker": "CVS",
        "cik": "0000064803",
        "name": "CVS Health",
        "bankrupt": 0,
        "sector": "Consumer Staples",
        "year_filed": None,
    },
    {
        "ticker": "MRK",
        "cik": "0000310158",
        "name": "Merck & Co",
        "bankrupt": 0,
        "sector": "Healthcare",
        "year_filed": None,
    },
]
