"""
Company universe: a curated list of public companies with known outcomes.

Each entry has:
  - ticker:    stock symbol (used by yfinance)
  - cik:       SEC EDGAR company ID (used to pull 10-K filings)
  - name:      human-readable company name
  - bankrupt:  1 = filed for bankruptcy, 0 = still operating/healthy
  - sector:    industry group for dashboard filters
  - year_filed: year bankruptcy was filed (None if healthy)

We chose well-known bankruptcies because their outcomes are verifiable
and their EDGAR filings are complete going back to the early 2000s.
"""

COMPANIES = [
    # ── BANKRUPT companies ─────────────────────────────────────────────────
    {
        "ticker": "ENRNQ",
        "cik": "0000101778",
        "name": "Enron Corp",
        "bankrupt": 1,
        "sector": "Energy",
        "year_filed": 2001,
    },
    {
        "ticker": "LEHMQ",
        "cik": "0000806517",
        "name": "Lehman Brothers",
        "bankrupt": 1,
        "sector": "Financials",
        "year_filed": 2008,
    },
    {
        "ticker": "GM",
        "cik": "0000040730",
        "name": "General Motors (old)",
        "bankrupt": 1,
        "sector": "Consumer Discretionary",
        "year_filed": 2009,
    },
    {
        "ticker": "SHLDQ",
        "cik": "0001310067",
        "name": "Sears Holdings",
        "bankrupt": 1,
        "sector": "Consumer Discretionary",
        "year_filed": 2018,
    },
    {
        "ticker": "RSHCQ",
        "cik": "0000096289",
        "name": "RadioShack",
        "bankrupt": 1,
        "sector": "Consumer Discretionary",
        "year_filed": 2015,
    },
    {
        "ticker": "CCTYQ",
        "cik": "0000200406",
        "name": "Circuit City",
        "bankrupt": 1,
        "sector": "Consumer Discretionary",
        "year_filed": 2008,
    },
    {
        "ticker": "BLOKQ",
        "cik": "0001085734",
        "name": "Blockbuster",
        "bankrupt": 1,
        "sector": "Consumer Discretionary",
        "year_filed": 2010,
    },
    {
        "ticker": "KMART",
        "cik": "0000055067",
        "name": "Kmart",
        "bankrupt": 1,
        "sector": "Consumer Staples",
        "year_filed": 2002,
    },
    {
        "ticker": "WCOM",
        "cik": "0000723527",
        "name": "WorldCom / MCI",
        "bankrupt": 1,
        "sector": "Telecom",
        "year_filed": 2002,
    },
    {
        "ticker": "WAMUQ",
        "cik": "0000933136",
        "name": "Washington Mutual",
        "bankrupt": 1,
        "sector": "Financials",
        "year_filed": 2008,
    },
    {
        "ticker": "CHTRQ",
        "cik": "0001091334",
        "name": "Charter Communications (old)",
        "bankrupt": 1,
        "sector": "Telecom",
        "year_filed": 2009,
    },
    {
        "ticker": "PCRXQ",
        "cik": "0001419041",
        "name": "Pactera (Nortel Networks)",
        "bankrupt": 1,
        "sector": "Technology",
        "year_filed": 2009,
    },
    {
        "ticker": "NORX",
        "cik": "0000072162",
        "name": "Nortel Networks",
        "bankrupt": 1,
        "sector": "Technology",
        "year_filed": 2009,
    },
    {
        "ticker": "AERAQ",
        "cik": "0000006201",
        "name": "American Airlines (old)",
        "bankrupt": 1,
        "sector": "Industrials",
        "year_filed": 2011,
    },
    {
        "ticker": "DALRQ",
        "cik": "0000027904",
        "name": "Delta Air Lines (old)",
        "bankrupt": 1,
        "sector": "Industrials",
        "year_filed": 2005,
    },

    # ── HEALTHY companies ──────────────────────────────────────────────────
    {
        "ticker": "AAPL",
        "cik": "0000320193",
        "name": "Apple Inc",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "MSFT",
        "cik": "0000789019",
        "name": "Microsoft Corp",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "GOOGL",
        "cik": "0001652044",
        "name": "Alphabet Inc",
        "bankrupt": 0,
        "sector": "Technology",
        "year_filed": None,
    },
    {
        "ticker": "AMZN",
        "cik": "0001018724",
        "name": "Amazon.com",
        "bankrupt": 0,
        "sector": "Consumer Discretionary",
        "year_filed": None,
    },
    {
        "ticker": "JPM",
        "cik": "0000019617",
        "name": "JPMorgan Chase",
        "bankrupt": 0,
        "sector": "Financials",
        "year_filed": None,
    },
    {
        "ticker": "JNJ",
        "cik": "0000200406",
        "name": "Johnson & Johnson",
        "bankrupt": 0,
        "sector": "Healthcare",
        "year_filed": None,
    },
    {
        "ticker": "XOM",
        "cik": "0000034088",
        "name": "ExxonMobil",
        "bankrupt": 0,
        "sector": "Energy",
        "year_filed": None,
    },
    {
        "ticker": "WMT",
        "cik": "0000104169",
        "name": "Walmart",
        "bankrupt": 0,
        "sector": "Consumer Staples",
        "year_filed": None,
    },
    {
        "ticker": "VZ",
        "cik": "0000732712",
        "name": "Verizon Communications",
        "bankrupt": 0,
        "sector": "Telecom",
        "year_filed": None,
    },
    {
        "ticker": "GE",
        "cik": "0000040554",
        "name": "General Electric",
        "bankrupt": 0,
        "sector": "Industrials",
        "year_filed": None,
    },
    {
        "ticker": "BA",
        "cik": "0000012927",
        "name": "Boeing Co",
        "bankrupt": 0,
        "sector": "Industrials",
        "year_filed": None,
    },
    {
        "ticker": "DAL",
        "cik": "0000027904",
        "name": "Delta Air Lines (new)",
        "bankrupt": 0,
        "sector": "Industrials",
        "year_filed": None,
    },
    {
        "ticker": "T",
        "cik": "0000732717",
        "name": "AT&T",
        "bankrupt": 0,
        "sector": "Telecom",
        "year_filed": None,
    },
    {
        "ticker": "CVS",
        "cik": "0000064803",
        "name": "CVS Health",
        "bankrupt": 0,
        "sector": "Consumer Staples",
        "year_filed": None,
    },
    {
        "ticker": "MRK",
        "cik": "0000310158",
        "name": "Merck & Co",
        "bankrupt": 0,
        "sector": "Healthcare",
        "year_filed": None,
    },
]
